droneData = {
  51: {
    name: "JsonPlaceholderApi Test Site",
    description: "First verifies that it can retrieve a user.  Then confirms able to insert a user.",
    droneType: "watch",
    droneBase: "droneRemServ",
    uri: "https://jsonplaceholder.typicode.com",
    port: '',
    headers: [],
    active: true,
    checkInterval: 10,
    checkInterval_on_fail: 3,
    continue: true,
    cycleSuccessMsg: 'Verified Get user and Add user',
    cycleType: 'count',
    cycleCount: 0,
    cycle: 2,
    alertGroup: 1,
    alertSchedule: 1,  
    errStatus: false,
    errThreshold: 1,
    errCount: 0,   
    moduleKit: [
      {
        mod_id: '5d30cc309c37a300b5445e05',
        name: 'Verify Get User',
        url: '/users/1',
        port: '',
        addHeaders: [],
        requestType: "get",
        timeout: 10000,
        statusGood: 200,
        returnType: 'json',
        dataPost: {},
        dataReturn: {
          username: "Bret",
          address: {
            city: 'Gwenborough',
            geo: {
                lat: "-37.3159",
            }
          }
        },
        authType: {
          type: '',
          user: '',
          pass: '',
          key: '',
        },   
        authTrigger: '',
      },
      {
        mod_id: '5d30cccc6c939300cfa7332f',
        name: 'Verify Post User',
        url: '/posts',
        port: '',
        addHeaders: [],
        requestType: "POST",
        statusGood: 201,
        returnType: 'json',
        dataPost: {
          "userId" : "17",
          "name" : "John Jacob",
          "email" : "pelentan@gmail.com"
        },
        dataReturn: {
          "id" : "",
          "userId" : "17",
          "name" : "John Jacob",
          "email" : "pelentan@gmail.com"
        },
        authType: {
          type: '',
          user: '',
          pass: '',
          key: '',
        },
      },
    ],
  },
  1: {
    droneType: "watch",
    name: "LendPro Server",
    description: "Verifies that the login page is accessible",
    droneBase: "droneRemServ",
    uri: "https://qa60.mylendpro.com/",
    port: '',
    headers: [],
    active: true,
    checkInterval: 10,
    checkInterval_on_fail: 3,
    continue: true,
    cycleSuccessMsg: 'Verified Login Page',
    cycleType: 'count',
    cycleCount: 0,
    cycle: 2,
    alertGroup: 1,
    alertSchedule: 1,  
    errStatus: false,
    errThreshold: 1,
    errCount: 0,   
    moduleKit: [
      {
        mod_id: '5d30cd45a13e7500e9461194',
        url: '',
        port: '',
        addHeaders: [],
        requestType: "get",
        timeout: 10000,
        statusGood: 200,
        returnType: 'html',
        bodyScrape: "login",
        dataPost: {},
        dataReturn: {},
        authType: {
          type: '',
          user: '',
          pass: '',
          key: '',
        },   
      },
    ],
  }, 
  71: {
    name: "HC Mongo server test",
    description: "Verifies SSH access.  Runs specified tests on server.  Downloads results file",
    droneType: "watch",
    droneBase: "droneRemServ",
    uri: "hc-mongo",
    port: 22,
    headers: [],
    active: true,
    checkInterval: 3,
    checkInterval_on_fail: 3,
    continue: true,
    cycleSuccessMsg: 'Server root checks passed',
    cycleType: 'count',
    cycleCount: 0,
    cycle: 1,
    alertGroup: 1,
    alertSchedule: 1,  
    errStatus: false,
    errThreshold: 1,
    errCount: 0,   
    moduleKit: [
      {
        mod_id: '5d30cf250a409c01035d96a6',
        name: 'Verify Connection',
        url: '',
        port: 22,
        addHeaders: [],
        requestType: "",
        timeout: 10000,
        statusGood: 200,
        returnType: 'lynux',
        dataPost: {},
        dataReturn: {},
        authInfo: {
          type: 'privateKey',
          user: 'hcdronedock',
          pass: 'togatoga',
          key: 'remote_servers/hc-mongo/hc_npp',
        },   
        authTrigger: true,
      },
      {
        mod_id: '5d30c932ca42800057eb1936',
        name: 'Initiate server test-script(s) and retrive log file of results.',
        url: '',
        port: 22,
        addHeaders: [],
        requestType: "",
        statusGood: 200,
        returnType: 'json',
        dataPost: {
          "command": "bash",
          "script": "hc_server_checks.hc",
          "arguments": [
            1,
            3,
            "hc-server-report.hc"
          ],
          "exitCode": true,
          "exitCodePass": 0,
        },
        dataReturn: {
          "returnFile": "hc-server-report.hc",
          'fileScrap': ['toga', 'blue'],
        },
        authInfo: {
          type: 'privateKey',
          user: 'hcdronedock',
          pass: 'togatoga',
          key: 'hc_npp',
        },
        authTrigger: true,
      },
    ],
  },
}

