version: '3.7'
services:
    health-check:
        container_name: health-check
        image: health-check
        build:
            context: .
            dockerfile: .docker/node.dockerfile
        command: npm run dev
        env_file: 
            - ./.docker/env_files/hc_app_dev.env
        volumes:
          - .:/node/app
          - /node/app/node_modules
          - .node_logs:/root/.npm/
        # expose:
        #     - ${APP_PORT}
        networks:
            - node-net
            - lendDocNet
            - traefik
        labels:            
            - traefik.frontend.rule=Host:health-check.mylendpro.com
            - traefik.port=${APP_PORT}
            - traefik.docker.network=traefik
            - traefik.backend=health-check 
            - traefik.enable=true          
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: 
                    - node.labels.trused == true
            restart_policy:
                condition: on-failure
            labels:
            - "traefik.port=8080"
            - "traefik.frontend.rule=Host:registry.mylendpro.com"
            - "traefik.docker.network=traefik"  
            - "traefik.enable=true"
    hc-redis:
        container_name: hc-redis
        image: redis:alpine
        networks:
            - node-net
        labels:
            - traefik.enable=false  
        deploy:
            mode: global
            placement:
                constraints: 
                    - node.labels.trusted == true
            restart_policy:
                condition: on-failure
            labels: 
                - "traefik.enable=false"
    hc-mongo:
        container_name: hc-mongo
        build:
            context: .
            dockerfile: .docker/mongo.dockerfile
        image: hc-mongo        
        env_file: 
            - ./.docker/env_files/hc_mongo_dev.env
        networks:
            - node-net
        labels:
            - traefik.enable=false
        volumes:
            - hc-mongo-db:/data/db            
        deploy:
          mode: global
          placement:
            constraints: 
            - node.labels.registry == true
          restart_policy:
            condition: on-failure
          labels: 
            - "traefik.enable=false"

    hc-mongo-express:
        container_name: hc-monex
        image: mongo-express
        ports:
           - 8881:8081
        env_file: 
            - ./.docker/env_files/hc_mongo_exp.env        
        networks:
            - node-net
        labels:
            - traefik.frontend.rule=Host:hc-mongx.mylendpro.com
            - traefik.port=8081 
            - traefik.docker.network=traefik
            - traefik.backend=hc-mongx 
            - traefik.enable=true
        deploy:
          mode: global
          placement:
            constraints: 
                - node.labels.trusted == true
          restart_policy:
            condition: on-failure
          labels: 
            - traefik.frontend.rule=Host:hc-mongx.mylendpro.com
            - traefik.port=8081 
            - traefik.docker.network=traefik
            - traefik.backend=hc-mongx 
            - traefik.enable=true
            
volumes:
    hc-mongo-db:
        external: true

networks:
    node-net:
        external: false
    traefik:
        external: true
    lendDocNet:
        external: true